misconception_explanations = {
    '31772': [{'Label': 'Incomplete',
               'LabelLong': 'Incomplete',
               'Explanation': 'The student correctly identifies that the unshaded fraction is 3 out of 9, but they do not simplify the fraction to its simplest form as the question asks.'},
              {'Label': 'WNB',
               'LabelLong': 'Wrong Numerator and/or Base',
               'Explanation': 'The student may have counted the shaded parts (6) instead of the total parts (9) for the denominator, leading to an incorrect fraction like 3/6.'}],
    '31774': [{'Label': 'SwapDividend',
               'LabelLong': 'Swap Dividend and Divisor',
               'Explanation': 'The student may have swapped the numbers in the division, calculating 6 divided by 2, which incorrectly gives 3.'},
              {'Label': 'Mult',
               'LabelLong': 'Multiplication',
               'Explanation': "Instead of dividing, the student might have multiplied the fraction's numerator by the whole number, calculating 1/2 * 6 = 3."},
              {'Label': 'FlipChange',
               'LabelLong': "Incorrect 'Flip and Change'",
               'Explanation': "The student remembers to change the operation to multiplication but forgets to 'flip' the whole number 6 into its reciprocal, 1/6, leading to an incorrect calculation."}],
    '31777': [{'Label': 'Incomplete',
               'LabelLong': 'Incomplete',
               'Explanation': 'The student correctly performs the first step of dividing 120 by 5 to get 24, but then forgets to complete the calculation by multiplying by 3.'},
              {'Label': 'Irrelevant',
               'LabelLong': 'Irrelevant Information/Calculation',
               'Explanation': 'A student might get confused and use the numbers in the wrong way, for example, by dividing 120 by the difference of the denominator and numerator (5-3=2) to get 60.'},
              {'Label': 'Wrong_Fraction',
               'LabelLong': 'Calculated Wrong Fraction',
               'Explanation': 'The student correctly calculates a fraction of the total but finds the number of blue counters (2/5 of 120 = 48) instead of the number of red counters.'}],
    '31778': [{'Label': 'Additive',
               'LabelLong': 'Assumes Additive Relationship',
               'Explanation': 'The student sees that 15 - 5 = 10 and incorrectly applies the same subtraction to the top number, calculating 9 - 5 = 4.'},
              {'Label': 'Irrelevant',
               'LabelLong': 'Irrelevant Information/Calculation',
               'Explanation': 'Not knowing how to find an equivalent fraction, the student might simply guess that A is 9 because the other numerator is 9.'},
              {'Label': 'WNB',
               'LabelLong': 'Wrong Numerator and/or Base',
               'Explanation': 'The student may have made a mistake when simplifying the fraction 9/15 or when trying to find the factor needed to change the denominator to 10.'},
              {'Label': 'Incomplete',
               'LabelLong': 'Incomplete',
               'Explanation': 'The student correctly simplifies 9/15 to 3/5 but does not know how to continue and incorrectly chooses 3 as the answer.'}],
    '32829': [{'Label': 'Not_variable',
               'LabelLong': 'Does Not Understand Variable Notation',
               'Explanation': 'The student may not understand that 2y means 2 multiplied by y, and instead treats it as 2 plus y.'},
              {'Label': 'Adding_terms',
               'LabelLong': 'Adding Terms',
               'Explanation': "The student incorrectly reads 2y as '2 + y' and solves the equation by subtracting 2 from 24 to get 22."},
              {'Label': 'Inverse_operation',
               'LabelLong': 'Incorrect Inverse Operation',
               'Explanation': 'The student knows a calculation with 2 is needed but uses the wrong operation, such as multiplying 24 by 2 to get 48.'}],
    '32833': [{'Label': 'Inversion',
               'LabelLong': 'Inversion',
               'Explanation': 'The student confuses multiplication with division and calculates 2/3 divided by 5, which equals 2/15.'},
              {'Label': 'Duplication',
               'LabelLong': 'Duplication',
               'Explanation': 'The student incorrectly multiplies both the numerator and the denominator by 5, resulting in the fraction 10/15.'},
              {'Label': 'Wrong_Operation',
               'LabelLong': 'Wrong Operation',
               'Explanation': 'The student mistakes the multiplication sign for an addition sign and incorrectly adds 5 and 2/3 together.'}],
    '32835': [{'Label': 'Whole_numbers_larger',
               'LabelLong': 'Whole Numbers are Larger',
               'Explanation': 'The student might ignore the decimal part of the numbers, thinking that the plain whole number 6 is somehow larger or more significant than the others.'},
              {'Label': 'Longer_is_bigger',
               'LabelLong': 'Longer Decimal is Bigger',
               'Explanation': 'The student incorrectly believes that the number with the most digits after the decimal point is the largest, causing them to choose 6.0001.'},
              {'Label': 'Ignores_zeroes',
               'LabelLong': 'Ignores Zeroes/Place Value',
               'Explanation': 'A student might compare 2 with 79 by ignoring the zeroes, thinking that 6.079 is bigger than 6.2 because 79 is bigger than 2.'},
              {'Label': 'Shorter_is_bigger',
               'LabelLong': 'Shorter Decimal is Bigger',
               'Explanation': 'Confusing decimals with fractions, a student might think that the number with the fewest decimal places is the largest, leading them to choose 6.'}],
    '33471': [{'Label': 'Wrong_fraction',
               'LabelLong': 'Calculated Wrong Fraction',
               'Explanation': 'The student correctly calculates a fractional part of the total but finds the number of yellow balls (9) instead of the number of green balls.'},
              {'Label': 'Incomplete',
               'LabelLong': 'Incomplete',
               'Explanation': "The student only completes the first step of the problem, finding what one-eighth of the total is (24 divided by 8 equals 3), but doesn't multiply to find the final answer."}],
    '33472': [{'Label': 'Adding_across',
               'LabelLong': 'Adding Across',
               'Explanation': 'The student incorrectly adds the numerators (1+2=3) and the denominators (3+5=8) separately to get 3/8.'},
              {'Label': 'Denominator-only_change',
               'LabelLong': 'Denominator-Only Change',
               'Explanation': 'The student finds a common denominator (15) but forgets to change the numerators, simply adding the original numerators (1+2=3) to get 3/15.'},
              {'Label': 'Incorrect_equivalent_fraction_addition',
               'LabelLong': 'Incorrect Equivalent Fraction Addition',
               'Explanation': 'The student correctly calculates the numerator (11) but then makes a mistake with the denominator, possibly by adding the two common denominators (15+15) to get 11/30.'}],
    '33474': [{'Label': 'Division',
               'LabelLong': 'Division',
               'Explanation': "The student might misunderstand the phrase 'fraction of this piece' and think it means to divide the amounts, leading them to choose the division option."},
              {'Label': 'Subtraction',
               'LabelLong': 'Subtraction',
               'Explanation': "The student focuses on the word 'eats' and incorrectly assumes this means something is taken away, leading them to choose the subtraction option."}],
    '76870': [{'Label': 'Unknowable',
               'LabelLong': 'Unknowable/Not Enough Information',
               'Explanation': "The student may not know the formula connecting a regular polygon's angles to its sides and therefore incorrectly concludes that the problem cannot be solved."},
              {'Label': 'Definition',
               'LabelLong': 'Definitional Error',
               'Explanation': 'The student may not understand what a regular polygon is or may not know the relationship between its interior and exterior angles.'},
              {'Label': 'Interior',
               'LabelLong': 'Using Interior Angle Incorrectly',
               'Explanation': 'The student incorrectly uses the interior angle (144°) in the formula to find the number of sides, instead of first calculating the exterior angle.'}],
    '89443': [{'Label': 'Positive',
               'LabelLong': 'Incorrect Sign/Positive',
               'Explanation': 'The student correctly finds that the difference between 8 and 5 is 3 but gets the sign wrong, possibly by ignoring the negative signs and just calculating 8 - 5 = 3.'},
              {'Label': 'Tacking',
               'LabelLong': 'Tacking/Incorrectly Combining',
               'Explanation': 'The student ignores that subtracting a negative is the same as adding, and instead combines the numbers as if it were -8 - 5 to get -13.'}],
    '91695': [{'Label': 'Wrong_term',
               'LabelLong': 'Finds Wrong Term',
               'Explanation': 'The student correctly finds the rule for the pattern (add 4) but only calculates the next term (Pattern 5) instead of Pattern 6.'},
              {'Label': 'Firstterm',
               'LabelLong': 'Misusing the First Term',
               'Explanation': 'The student might try to create a rule by incorrectly using the first term of the pattern, for example by multiplying the pattern number (6) by the first term (6) to get 36.'}],
    '104665': [{'Label': 'Base_rate',
                'LabelLong': 'Misinterpreting the Base Rate',
                'Explanation': 'The student might mistakenly believe the time is constant regardless of how many people work, or they might divide 192 by 3 to get 64 and think that is the answer.'},
               {'Label': 'Multiplying_by_4',
                'LabelLong': 'Multiplying by 4/Assuming Direct Proportion',
                'Explanation': 'The student sees that the number of people quadrupled and incorrectly assumes the time will also quadruple, multiplying 192 by 4 instead of dividing.'}],
    '109465': [{'Label': 'Certainty',
                'LabelLong': 'Confuses Likely with Certain',
                'Explanation': "The student understands that 0.9 is a high probability, but they incorrectly think this means the event is guaranteed to happen, choosing 'Certain' instead of 'Likely'."},
               {'Label': 'Scale',
                'LabelLong': 'Misunderstands Probability Scale',
                'Explanation': 'The student does not have a clear understanding of the probability scale from 0 (impossible) to 1 (certain) and cannot correctly place where 0.9 falls.'}]}
